# Generated by go2rpm 1.9.0
%bcond_without check

# https://github.com/golang/vuln
%global goipath         golang.org/x/vuln
%global forgeurl        https://github.com/golang/vuln
Version:                1.0.0

%gometa -f


%global common_description %{expand:
[mirror] the database client and tools for the Go vulnerability database.}

%global golicenses      LICENSE PATENTS
%global godocs          doc CONTRIBUTING.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        [mirror] the database client and tools for the Go vulnerability database

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
%gobuild -o %{gobuilddir}/bin/vuln %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck -t cmd
%endif

%files
%license LICENSE PATENTS
%doc doc CONTRIBUTING.md README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
