# Generated by go2rpm 1.9.0
%bcond_without check

# https://github.com/google/osv-scanner
%global goipath         github.com/google/osv-scanner
Version:                1.3.3

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -f


%global common_description %{expand:
Vulnerability scanner written in Go which uses the data provided by
https://osv.dev.}

%global golicenses      LICENSE
%global godocs          docs CHANGELOG.md CONTRIBUTING.md README.md\\\
                        pkg/lockfile/fixtures/cargo/not-toml.txt\\\
                        pkg/lockfile/fixtures/composer/not-json.txt\\\
                        pkg/lockfile/fixtures/conan/not-json.txt\\\
                        pkg/lockfile/fixtures/go/not-go-mod.txt\\\
                        pkg/lockfile/fixtures/maven/not-pom.txt\\\
                        pkg/lockfile/fixtures/npm/not-json.txt\\\
                        pkg/lockfile/fixtures/nuget/not-json.txt\\\
                        pkg/lockfile/fixtures/pip/cyclic-r-complex-1.txt\\\
                        pkg/lockfile/fixtures/pip/cyclic-r-complex-2.txt\\\
                        pkg/lockfile/fixtures/pip/cyclic-r-complex-3.txt\\\
                        pkg/lockfile/fixtures/pip/cyclic-r-self.txt\\\
                        pkg/lockfile/fixtures/pip/duplicate-r-base.txt\\\
                        pkg/lockfile/fixtures/pip/duplicate-r-dev.txt\\\
                        pkg/lockfile/fixtures/pip/duplicate-r-test.txt\\\
                        pkg/lockfile/fixtures/pip/empty.txt\\\
                        pkg/lockfile/fixtures/pip/file-format-example.txt\\\
                        pkg/lockfile/fixtures/pip/line-continuation.txt\\\
                        pkg/lockfile/fixtures/pip/multiple-packages-\\\
                        constrained.txt pkg/lockfile/fixtures/pip/multiple-\\\
                        packages-mixed.txt pkg/lockfile/fixtures/pip/non-\\\
                        normalized-names.txt pkg/lockfile/fixtures/pip/one-\\\
                        package-constrained.txt\\\
                        pkg/lockfile/fixtures/pip/one-package-\\\
                        unconstrained.txt pkg/lockfile/fixtures/pip/only-\\\
                        comments.txt pkg/lockfile/fixtures/pip/other-file.txt\\\
                        pkg/lockfile/fixtures/pip/with-added-support.txt\\\
                        pkg/lockfile/fixtures/pip/with-bad-r-option.txt\\\
                        pkg/lockfile/fixtures/pip/with-multiple-r-options.txt\\\
                        pkg/lockfile/fixtures/pip/with-per-requirement-\\\
                        options.txt pkg/lockfile/fixtures/pipenv/not-json.txt\\\
                        pkg/lockfile/fixtures/pnpm/not-yaml.txt\\\
                        pkg/lockfile/fixtures/poetry/not-toml.txt\\\
                        pkg/lockfile/fixtures/pub/not-yaml.txt

Name:           %{goname}
Release:        %autorelease
Summary:        Vulnerability scanner written in Go which uses the data provided by https://osv.dev

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc docs CHANGELOG.md CONTRIBUTING.md README.md
%doc pkg/lockfile/fixtures/cargo/not-toml.txt
%doc pkg/lockfile/fixtures/composer/not-json.txt
%doc pkg/lockfile/fixtures/conan/not-json.txt
%doc pkg/lockfile/fixtures/go/not-go-mod.txt
%doc pkg/lockfile/fixtures/maven/not-pom.txt
%doc pkg/lockfile/fixtures/npm/not-json.txt
%doc pkg/lockfile/fixtures/nuget/not-json.txt
%doc pkg/lockfile/fixtures/pip/cyclic-r-complex-1.txt
%doc pkg/lockfile/fixtures/pip/cyclic-r-complex-2.txt
%doc pkg/lockfile/fixtures/pip/cyclic-r-complex-3.txt
%doc pkg/lockfile/fixtures/pip/cyclic-r-self.txt
%doc pkg/lockfile/fixtures/pip/duplicate-r-base.txt
%doc pkg/lockfile/fixtures/pip/duplicate-r-dev.txt
%doc pkg/lockfile/fixtures/pip/duplicate-r-test.txt
%doc pkg/lockfile/fixtures/pip/empty.txt
%doc pkg/lockfile/fixtures/pip/file-format-example.txt
%doc pkg/lockfile/fixtures/pip/line-continuation.txt
%doc pkg/lockfile/fixtures/pip/multiple-packages-constrained.txt
%doc pkg/lockfile/fixtures/pip/multiple-packages-mixed.txt
%doc pkg/lockfile/fixtures/pip/non-normalized-names.txt
%doc pkg/lockfile/fixtures/pip/one-package-constrained.txt
%doc pkg/lockfile/fixtures/pip/one-package-unconstrained.txt
%doc pkg/lockfile/fixtures/pip/only-comments.txt
%doc pkg/lockfile/fixtures/pip/other-file.txt
%doc pkg/lockfile/fixtures/pip/with-added-support.txt
%doc pkg/lockfile/fixtures/pip/with-bad-r-option.txt
%doc pkg/lockfile/fixtures/pip/with-multiple-r-options.txt
%doc pkg/lockfile/fixtures/pip/with-per-requirement-options.txt
%doc pkg/lockfile/fixtures/pipenv/not-json.txt
%doc pkg/lockfile/fixtures/pnpm/not-yaml.txt
%doc pkg/lockfile/fixtures/poetry/not-toml.txt
%doc pkg/lockfile/fixtures/pub/not-yaml.txt
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
