# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/CycloneDX/cyclonedx-go
%global goipath         github.com/CycloneDX/cyclonedx-go
Version:                0.7.1

%gometa -f


%global common_description %{expand:
Go library to consume and produce CycloneDX Software Bill of Materials (SBOM).}

%global golicenses      LICENSE NOTICE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Go library to consume and produce CycloneDX Software Bill of Materials (SBOM)

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
