# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/spdx/tools-golang
%global goipath         github.com/spdx/tools-golang
Version:                0.5.3

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -f


%global common_description %{expand:
Collection of Go packages to work with SPDX files.}

%global golicenses      LICENSE.code LICENSE.docs docs/licensediff-\\\
                        assumptions.md licensediff/licensediff.go\\\
                        licensediff/licensediff_test.go\\\
                        spdx/v2/v2_2/rdf/reader/license_utils.go\\\
                        spdx/v2/v2_2/rdf/reader/license_utils_test.go\\\
                        spdx/v2/v2_3/rdf/reader/license_utils.go\\\
                        spdx/v2/v2_3/rdf/reader/license_utils_test.go
%global godocs          docs examples CONTRIBUTING.md README.md RELEASE-\\\
                        NOTES.md SECURITY.md example example

Name:           %{goname}
Release:        %autorelease
Summary:        Collection of Go packages to work with SPDX files

License:        CC-BY-4.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
