# Generated by go2rpm 1.9.0
%bcond_without check

# https://github.com/jedib0t/go-pretty
%global goipath         github.com/jedib0t/go-pretty/v6
Version:                6.4.6

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -f


%global common_description %{expand:
Table-writer and more in golang!}

%global golicenses      LICENSE
%global godocs          CODE_OF_CONDUCT.md README.md SECURITY.md cmd/demo-\\\
                        list/README.md cmd/demo-progress/README.md cmd/demo-\\\
                        table/README.md list/README.md progress/README.md\\\
                        table/README.md text/README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Table-writer and more in golang

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc CODE_OF_CONDUCT.md README.md SECURITY.md cmd/demo-list/README.md
%doc cmd/demo-progress/README.md cmd/demo-table/README.md list/README.md
%doc progress/README.md table/README.md text/README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
